### ISSUE TITLE
When selecting 'other' no free text option offered

### ISSUE THREAD

**Issue by outbreakprepared** [open-covid-data/healthmap-gdo-temp#328]
**Describe the bug**
When selecting 'other' in fields: Transmission and Place of transmission no free text option is offered.

**To Reproduce**
1. Go to 'Route of transmission'
2. Click on 'select other'

**Expected behavior**
Free text option offered.

**Screenshots**

**Environment (please complete the following information):**
 - OS
 - chrome
 -  83.0.4103.116

**Comment by attwad** [comment]
The schema that we have (enum for routes) seems to imply that we just store "other" and don't care about the actual value, @khmoran was this intentional? Perhaps we should change this from an enum to a string and remove exact validation on terms entered there. OR if one selects "others" we can have a different field for what it is,  a bit more complex but we keep validation on most common transmission routes. Considering we already suggest them I think people are not going to enter gargabe data so changing to string seems the easiest imo.

**Comment by khmoran** [comment]
Not intentional - agree we should make it a string field instead of enum

**Comment by attwad** [comment]
Geez it's 3am over there, are the fireworks that bad? 😨 
thanks for the reply ;-) I'll try to do the change today.

**Comment by khmoran** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Allow free-form text entry for "Other" fields](https://trello.com/c/BhMc3HjT/275-allow-free-form-text-entry-for-other-fields)

**Comment by allysonjp715** [comment]
Fields that should have free text options after selecting other:
- places of transmission
- method of travel
- Occupation
