### ISSUE TITLE
Manual entry form: Once submitted path to submit another case

### ISSUE THREAD

**Issue by sratcliffe118** [open-covid-data/healthmap-gdo-temp#449]
Steps to repeat

- Fill in manual entry form
- Click submit
- Form submits successful and see message
- Navigate to 'New' to enter a new line list
- Form reopens with all the data from previous entry still populated

Expected 
- User should have a quick path to navigate to the form to enter another line list case
- The form should be cleared of all data so the user can start the process again

AI: Will raise a feature request for dealing with multiple cases with the same data

**Comment by allysonjp715** [comment]
+ @shroothless for UI guidance here

**Comment by shroothless** [comment]
On repeat entry, I agree "The form should be cleared of all data so the user can start the process again"

**Comment by allysonjp715** [comment]
Perhaps we could use this bug to track the whole flow after hitting submit? 

Currently if you click another menu button then click back to +New it will reset the form to empty values. It's just that when you are on the form entry page and click on the +New menu button it doesn't reset the fields because you are already on that URL. We could probably change that, but probably best to think through the whole flow now.

**Comment by shroothless** [comment]
The creation flow should be in a modal and the menu should not be available. 
![image](https://user-images.githubusercontent.com/67452108/86957660-07fc0c00-c129-11ea-8f86-4ea59d362c65.png)

**Comment by shroothless** [comment]
So you should not be able to select new when you are in form entry. Please let me know if I'm not understanding the problem

**Comment by allysonjp715** [comment]
Sounds good, and I just remembered this mock for what page should be shown once the case is added. Will do.

![Screen Shot 2020-07-13 at 11 05 38 AM](https://user-images.githubusercontent.com/30459667/87292511-d43e2f00-c4f8-11ea-83c8-4f4f40114a33.png)
