### ISSUE TITLE
Original data case ID missing

### ISSUE THREAD

**Issue by outbreakprepared** [open-covid-data/healthmap-gdo-temp#454]
**Is your feature request related to a problem? Please describe.**

Case ID from original source could not be entered into the form.

**Describe the solution you'd like**
Add field that allows to enter ID from source.

![Screenshot 2020-07-07 at 12 02 45](https://user-images.githubusercontent.com/63060519/86771248-cb0d1800-c049-11ea-82d7-e27f30b22090.png)

**Describe alternatives you've considered**
Considered to put in notes field.

**Comment by allysonjp715** [comment]
Over to Shru to spec out

**Comment by shroothless** [comment]
Is the ask to enter an ID instead of a URL, in addition to? I'm sorry I'm not following.

**Comment by allysonjp715** [comment]
Sorry should've put some more information in from conversations we've been having. There will be two IDs: one ID is the ID we create for our database. This is the "Unique Case ID" in the schema, and will be generated by our database and not entered by the user. There is another ID called the "Data Source ID" in the schema, which is what this bug is requesting. Some sources provide their own IDs distinguishing cases for just that one source. We want the curators to copy the ID provided by the source and enter it as a "Data Source ID". 

Let me know if you need more details!

**Comment by shroothless** [comment]
Per our chat, let's try this. Let me know if you need anything else. @sratcliffe118 prolly need to reflect this in the schema too.

![image](https://user-images.githubusercontent.com/67452108/87968296-30bbc400-ca8e-11ea-86e7-fb3114fbaae4.png)

**Comment by allysonjp715** [comment]
Thanks, Shroo! Ah, yes, I had it wrong when I said this was the "Data Source ID" from the schema. That row was referring to an ID for the entire source document. We'll need to add another row in the linelist model doc for the source entry ID.
