### ISSUE TITLE
Cannot login to curator portal when have multiple accounts in Chrome 

### ISSUE THREAD

**Issue by sratcliffe118** [open-covid-data/healthmap-gdo-temp#486]
Cannot login to curator portal when have multiple accounts in Chrome

**Comment by attwad** [comment]
Yup, known issue but I haven't been able to figure out why this is happening yet...
As a short-term solution until we figure out what's going on with the passport.js integration I suggest moving to different chrome profiles instead of signing into multiple account in the same chrome profile. This is what I use personally between my work/personal profile, it gives you synchronization across all profiles and a clearer/cleaner separation of stuff (history, bookmarks, stored passwords, etc).

https://support.google.com/chrome/answer/2364824?co=GENIE.Platform%3DDesktop&hl=en

**Comment by attwad** [comment]
Okay I found the solution in https://github.com/jaredhanson/passport-google-oauth2/issues/18 and verified that it worked, will send a fix.
