### ISSUE TITLE
Bulk upload CSV template sheet: Hospitalized options fail validation

### ISSUE THREAD

**Issue by sratcliffe118** [open-covid-data/healthmap-gdo-temp#529]
Steps to recreate
1. Select true or false as a value in the hospitalized field
2. Try to upload the CSV to the database
3. Receive an error message 422, file could not be 

Hospitalized field if true or false is selected for upload then it fails the upload. Also a validation message is shown within the CSV, see attached.

[uploaded](url
![Screen Shot 2020-07-13 at 1 13 49 PM](https://user-images.githubusercontent.com/63205311/87303237-bb3e7980-c50a-11ea-986e-b82b1d696774.png)
)

**Comment by axmb** [comment]
Couldn't exactly confirm, since dev has been updated a couple times, but I can see the issue.

1. I've changed the official Sheets template to treat the `hospitalized` column as plain text, to prevent it upper-casing the values. This would have solved the issue in the version of dev above.
2. I've made the handling logic for `hospitalized` a little more strict. We can add some client-side validation down the line, to get better error messages.
